#######################################################################
###                   Key-Value Stream Options                      ###
#######################################################################

# 모니터링할 스트림 ID 목록
stream_ids = ["000000000000000000000000000000000000000000000000000000000000f2bd"]

#######################################################################
###                     DB Config Options                           ###
#######################################################################

# 데이터 저장 디렉토리
db_dir = "db"
# KV 메타데이터 저장 디렉토리
kv_db_dir = "kv.DB"

#######################################################################
###                     Log Sync Config Options                     ###
#######################################################################

# 블록체인 RPC 엔드포인트
blockchain_rpc_endpoint = "https://rpc.0g.ai"
# 로그 컨트랙트 주소
log_contract_address = "0x0000000000000000000000000000000000000000"
# 로그 동기화 시작 블록 번호
log_sync_start_block_number = 0

#######################################################################
###                     RPC Config Options                          ###
#######################################################################

# RPC 서비스 제공 여부
rpc_enabled = true

# 공개 RPC를 위한 HTTP 서버 주소
rpc_listen_address = "0.0.0.0:6789"

# 데이터 다운로드를 위한 0G 스토리지 노드 URL
zgs_node_urls = "https://rpc.0g.ai"

#######################################################################
###                     Misc Config Options                         ###
#######################################################################

log_config_file = "log_config" 